apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: containerbuilds.art.openshift.io
spec:
  group: art.openshift.io
  names:
    kind: ContainerBuild
    listKind: ContainerBuildList
    plural: containerbuilds
    singular: containerbuild
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: ContainerBuild is the Schema for the containerbuilds API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: ContainerBuildSpec defines the desired state of ContainerBuild
          type: object
        status:
          description: ContainerBuildStatus defines the observed state of ContainerBuild
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
