apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-engine-prototype
spec:
  replicas: 1
  selector:
    matchLabels:
      name: release-engine-prototype
  template:
    metadata:
      labels:
        name: release-engine-prototype
    spec:
      serviceAccountName: release-engine-prototype
      containers:
        - name: release-engine-prototype
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - release-engine-prototype
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "release-engine-prototype"
