// +build !ignore_autogenerated

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/vfreex/release-engine-prototype/pkg/apis/art/v1alpha1.ContainerBuild":       schema_pkg_apis_art_v1alpha1_ContainerBuild(ref),
		"github.com/vfreex/release-engine-prototype/pkg/apis/art/v1alpha1.ContainerBuildSpec":   schema_pkg_apis_art_v1alpha1_ContainerBuildSpec(ref),
		"github.com/vfreex/release-engine-prototype/pkg/apis/art/v1alpha1.ContainerBuildStatus": schema_pkg_apis_art_v1alpha1_ContainerBuildStatus(ref),
	}
}

func schema_pkg_apis_art_v1alpha1_ContainerBuild(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "ContainerBuild is the Schema for the containerbuilds API",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/vfreex/release-engine-prototype/pkg/apis/art/v1alpha1.ContainerBuildSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/vfreex/release-engine-prototype/pkg/apis/art/v1alpha1.ContainerBuildStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/vfreex/release-engine-prototype/pkg/apis/art/v1alpha1.ContainerBuildSpec", "github.com/vfreex/release-engine-prototype/pkg/apis/art/v1alpha1.ContainerBuildStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_art_v1alpha1_ContainerBuildSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "ContainerBuildSpec defines the desired state of ContainerBuild",
				Type:        []string{"object"},
			},
		},
	}
}

func schema_pkg_apis_art_v1alpha1_ContainerBuildStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "ContainerBuildStatus defines the observed state of ContainerBuild",
				Type:        []string{"object"},
			},
		},
	}
}
